// <auto-generated />
namespace Passionproject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class second_m : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(second_m));
        
        string IMigrationMetadata.Id
        {
            get { return "202102232225046_second_m"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
