// <auto-generated />
namespace Passionproject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20212402109 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20212402109));
        
        string IMigrationMetadata.Id
        {
            get { return "202102241809218_20212402109"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
